<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAPTEST_A00" name="Navegacion_Header" tests="4" failures="1" timestamp="17 Aug 2017 15:02:51 GMT" time="11.189" errors="0">
  <testcase name="NuevosAlumnos" time="0.662" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumnos" time="1.824" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumni" time="1.277" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Empresas" time="0.62" classname="Salle.TestClasses.SalleHeader">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at Salle.TestClasses.SalleHeader.Empresas(SalleHeader.java:96)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Empresas -->
</testsuite> <!-- Navegacion_Header -->
