<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5OUND92" name="Navegacion_Header1" tests="5" failures="1" timestamp="17 Nov 2017 12:17:28 GMT" time="24.127" errors="0">
  <testcase name="NuevosAlumnos" time="4.978" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumnos" time="2.53" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumni" time="2.354" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Empresas" time="1.367" classname="Salle.TestClasses.SalleHeader">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at Salle.TestClasses.SalleHeader.Empresas(SalleHeader.java:82)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- Empresas -->
  <testcase name="Universidades" time="1.146" classname="Salle.TestClasses.SalleHeader"/>
</testsuite> <!-- Navegacion_Header1 -->
